(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
(** MASSES GeV **)

md=4.8 10^-3;
mu=2.3 10^-3;
ms=95 10^-3;
mc=1.275;
mt=170;
mb=4.4;
Cmu=0.3355;
Cmd=0.3395;
Cms=0.486;
Cmc=1.550;
Cmb=4.730;
mw=80.385;

me=0.51099895000*10^-3;
m\[Mu]=105.6583755*10^-3;
m\[Tau]=1776.86*10^-3;

MCC=3.0969;
MB=5.279;
MBc=6.274;
MBc2=6.871;
MD=1869.58*10^-3;
MDs=1968.47*10^-3;
M\[CapitalUpsilon]1=9.46;
M\[CapitalUpsilon]3=10.3552;
MB0=5.27955;
mks=0.89166;(*K STAR MASS*)
mk=0.497611;
M\[Pi]=139.57061*10^-3;
mRhoplus=0.776
mPiplus=0.13957018; (*Pi+*)
mPi0=0.1349766;(*Pi0*)
mK0=0.497614; (*K0*)
mKplus=0.493677;(*K+*)
mKst=0.896;
mDs={1.96849,0.00032};(*Ds plus *)
mDplus=1.86962;
mDzero=1.86486;
mBplus=5.27925;
mBs=5.36689;
mBc=6.2751; 
m\[Eta]c=2.9836;


(** DECAY CONSTANTS GeV**)

f\[Pi]=130.7*10^-3;
f\[Rho]=.223;
fk=155.8*10^-3;
fks=.217;
fB=189.9*10^-3;
fBs=0.225;
fJ=0.401
fD=211.9*10^-3; 
fBc=0.434;
fDs=0.249;
f\[CapitalUpsilon]T=0.659;
f\[CapitalUpsilon]1=649*10^-3;
f\[CapitalUpsilon][2]=0.468;
f\[CapitalUpsilon][3]=539*10^-3;
f\[CapitalUpsilon][4]=0.349;

eps=1.6*10^-3;

(** CKM ENTRIES **)
VCKMw[\[Lambda]_,\[Rho]_,A_,\[Eta]_]:={{1-\[Lambda]^2/2-\[Lambda]^4/8,\[Lambda],A*\[Lambda]^3*(\[Rho]-I \[Eta])},{-\[Lambda] (1+A^2\[Lambda]^4*(\[Rho]+I* \[Eta]-1/2)),1-\[Lambda]^2/2-\[Lambda]^4/8*(1+4*A^2),A*\[Lambda]^2},
{A*\[Lambda]^3(1-(\[Rho]+I*\[Eta])(1-\[Lambda]^2/2)),-A*\[Lambda]^2(1+\[Lambda]^2(\[Rho]+I \[Eta]-1/2)),1-A^2/2*\[Lambda]^4}}

Vudw[{\[Lambda]_,\[Rho]_,A_,\[Eta]_}]:=VCKMw[\[Lambda],\[Rho],A,\[Eta]][[1,1]]
Vusw[{\[Lambda]_,\[Rho]_,A_,\[Eta]_}]:=VCKMw[\[Lambda],\[Rho],A,\[Eta]][[1,2]]
Vubw[{\[Lambda]_,\[Rho]_,A_,\[Eta]_}]:=VCKMw[\[Lambda],\[Rho],A,\[Eta]][[1,3]]

Vcdw[{\[Lambda]_,\[Rho]_,A_,\[Eta]_}]:=VCKMw[\[Lambda],\[Rho],A,\[Eta]][[2,1]]
Vcsw[{\[Lambda]_,\[Rho]_,A_,\[Eta]_}]:=VCKMw[\[Lambda],\[Rho],A,\[Eta]][[2,2]]
Vcbw[{\[Lambda]_,\[Rho]_,A_,\[Eta]_}]:=VCKMw[\[Lambda],\[Rho],A,\[Eta]][[2,3]]

Vtdw[{\[Lambda]_,\[Rho]_,A_,\[Eta]_}]:=VCKMw[\[Lambda],\[Rho],A,\[Eta]][[3,1]]
Vtsw[{\[Lambda]_,\[Rho]_,A_,\[Eta]_}]:=VCKMw[\[Lambda],\[Rho],A,\[Eta]][[3,2]]
Vtbw[{\[Lambda]_,\[Rho]_,A_,\[Eta]_}]:=VCKMw[\[Lambda],\[Rho],A,\[Eta]][[3,3]]

(* UTfit *)
\[Lambda]ut={0.22534,0.00065};
\[Rho]ut={0.132,0.023};
Aut={0.821,0.012};
\[Eta]ut={0.352,0.014};

(* Central values *)
Vud=Vudw[{\[Lambda]ut[[1]],\[Rho]ut[[1]],Aut[[1]],\[Eta]ut[[1]]}];
Vus=Vusw[{\[Lambda]ut[[1]],\[Rho]ut[[1]],Aut[[1]],\[Eta]ut[[1]]}];
Vub=Vubw[{\[Lambda]ut[[1]],\[Rho]ut[[1]],Aut[[1]],\[Eta]ut[[1]]}];
Vcd=Vcdw[{\[Lambda]ut[[1]],\[Rho]ut[[1]],Aut[[1]],\[Eta]ut[[1]]}];
Vcs=Vcsw[{\[Lambda]ut[[1]],\[Rho]ut[[1]],Aut[[1]],\[Eta]ut[[1]]}];
Vcb=Vcbw[{\[Lambda]ut[[1]],\[Rho]ut[[1]],Aut[[1]],\[Eta]ut[[1]]}];
Vtd=Vtdw[{\[Lambda]ut[[1]],\[Rho]ut[[1]],Aut[[1]],\[Eta]ut[[1]]}];
Vts=Vtsw[{\[Lambda]ut[[1]],\[Rho]ut[[1]],Aut[[1]],\[Eta]ut[[1]]}];
Vtb=Vtbw[{\[Lambda]ut[[1]],\[Rho]ut[[1]],Aut[[1]],\[Eta]ut[[1]]}];


(* ::Input::Initialization:: *)
(* check *)
VCKMw[\[Lambda],\[Rho],A,\[Eta]]//MatrixForm
Series[Det[%],{\[Lambda],0,5}]//Simplify

VCKMc=VCKMw[\[Lambda]ut[[1]],\[Rho]ut[[1]],Aut[[1]],\[Eta]ut[[1]]];
%//MatrixForm
%//Abs//MatrixForm


(* ::Input::Initialization:: *)
(** COUPLING CONSTANTS **) 
Gf=1.166*10^-5;
\[Alpha]em=1/129;

(** DECAY WIDTHS/DECAY TIME & \[Rho]  **)
tauKplus={1.2380 10^-8,0.0021 10^-8}/(6.582 10^-25);
tauKL={5.116 10^-8,0.021 10^-8}/(6.582 10^-25);
tauDplus={1.040,0.007}*10^-12/(6.582 10^-25);
tauDzero={4.101,0.015}*10^-13/(6.582 10^-25);
tauPiplus = {2.6033, 0.0005}*10^-8/(6.582 10^-25);
tauDs={5,0.07}10^-13/(6.582 10^-25);
tauBplus={1641,8}10^-15/(6.582 10^-25);
tauBzero={1.519,0.004}10^-12/(6.582 10^-25);
tauTau={2.906,0.010}10^-13/ (6.582 10^-25);
tauBc={0.507,0.009}10^-12/ (6.582 10^-25);
tauCC=(7.9*10^-21)/ (6.582 10^-25);

\[CapitalGamma]bs=1/(1.620*10^\[Minus]12*(1.52*10^24));
\[CapitalGamma]b=1/(1.641*10^\[Minus]12*(1.52*10^24));
\[CapitalGamma]D=1/(1040*10^-15*(1.52*10^24));
\[CapitalGamma]Ds=1/((5.00)*10^-13*(1.52*10^24));
\[CapitalGamma]\[CapitalUpsilon]1=54.022*10^-6;
\[CapitalGamma]\[CapitalUpsilon][2]=31.98*10^-6;
\[CapitalGamma]\[CapitalUpsilon][3]=20.32*10^-6;
\[CapitalGamma]\[CapitalUpsilon][4]=20.5*10^-3;
\[CapitalGamma]k=1/((1.2380*10^-8)*(1.52*10^24));



